### ISSUE TITLE
结果文件解读

### ISSUE THREAD

**Issue by hq66** [zhangrengang/Centromics#17]
你好，十分感谢你，Centromics是一款很好用的软件，输入文件及参数非常详细。但是输出文件缺乏基本的介绍，我有以下2个疑问：
1.输出文件*.trf.count是一个bed文件，后6列为串联重复的计数，但是在我的文件中，出现了$4>$3-$2的行，请问这是软件本身统计的失误，还是我对计数的理解有误？
HiC_scaffold_1  40260000        40270000        10140.0 9928.0  0       0       0
HiC_scaffold_1  40270000        40280000        9879.0  9684.0  0       0       0
HiC_scaffold_1  40280000        40290000        10129.0 9923.0  0       0       0
HiC_scaffold_1  40290000        40300000        9876.0  9681.0  0       0       0
HiC_scaffold_1  40300000        40310000        10137.0 9924.0  0       0       0
2.输出文件*.trf.fa为如下的各串联重复的序列，每一条序列中的如N=2285，weight=0.42，ratio=0.523%这三个参数如何理解，在*.trf.count文件中，计数似乎远大于N这个数值。
>CL1 N=2285;L=262;center=TR3376;weight=0.42;ratio=0.523%
TAACAGAGTGTTACTGTTCACAGAAAGCGCTAAACTGAGCGTT……

**Comment by zhangrengang** [comment]
1. 因为可能会计入跟window边缘重叠的hits，所以略高于window size应该是可能的。
2. N是从reads中统计的基序出现的数量，*.trf.count是基因组上的，二者不一致。weight是聚类上的参数，可以不用管。ratio是串联重复在reads中的占比。

**Comment by hq66** [comment]
非常感谢您的解答。
