### ISSUE TITLE
软件运行报错

### ISSUE THREAD

**Issue by Guoshuai1314** [zhangrengang/Centromics#5]
您好，我在使用Centromics检测着丝粒区域的时候一直报错，报错内容如下：
![Snipaste_2023-06-27_09-27-36](https://github.com/zhangrengang/Centromics/assets/34433012/c1f33600-85ae-488e-9e17-e463fbb167a5)
我们的物种单染色体比较大，blastn的时候query太大导致内存溢出，这个需要怎么解决呢？

**Comment by zhangrengang** [comment]
这个似乎没有好法，换大内存服务器或试试单条染色体运行？或者分割染色体？
